---
- set_fact:
    repo_group_dest: "{{ repo_group.dir }}"

- name: "Ensure {{ repo_group_dest }} exists"
  file:
    path: "{{ repo_group_dest }}"
    state: directory

- name: "Clone repos"
  include_tasks: ./clone_repo.yml
  loop: "{{ repo_group.repos }}"
  vars:
    repo: "{{ item }}"

