---
- name: Download and install anki
  include_tasks: util/download_file.yml
  vars:
    dl_url: "https://github.com/ankitects/anki/releases/download/23.10.1/anki-23.10.1-linux-qt6.tar.zst"
    dl_filename: "anki.tar.zst"
    dl_unarchive: yes
    dl_unarchive_dir: "{{ dotfiles_data_dir }}/anki"
    dl_link_file_path: "{{ dl_unarchive_dir }}/anki-23.10.1-linux-qt6/anki"
    dl_link_file_dest: "/usr/local/bin/anki"
