---
- name: Download and install lazygit
  include_tasks: util/download_file.yml
  vars:
    dl_url: "https://github.com/jesseduffield/lazygit/releases/download/v0.36.0/lazygit_0.36.0_Linux_x86_64.tar.gz"
    dl_filename: "lazygit.tar.gz"
    dl_unarchive: yes
    dl_unarchive_dir: "{{ dotfiles_data_dir }}/lazygit"
    dl_link_file_path: "{{ dl_unarchive_dir }}/lazygit"
    dl_link_file_dest: "/usr/local/bin/lg"

