---
- name: Download and install lf
  include_tasks: util/download_file.yml
  vars:
    dl_url: "{{ software_lf_binary }}"
    dl_filename: "lf.tar.gz"
    dl_unarchive: yes
    dl_unarchive_dir: "{{ confdir }}/lf"
    dl_link_file_path: "{{ dl_unarchive_dir }}/lf"
    dl_link_file_dest: "/usr/local/bin/lf"

