---
- name: Download and install lf
  include_tasks: util/download_file.yml
  vars:
    dl_url: "https://github.com/gokcehan/lf/releases/latest/download/lf-linux-amd64.tar.gz"
    dl_filename: "lf.tar.gz"
    dl_unarchive: yes
    dl_unarchive_dir: "{{ dotfiles_data_dir }}/lf"
    dl_link_file_path: "{{ dl_unarchive_dir }}/lf"
    dl_link_file_dest: "/usr/local/bin/lf"

- name: Install some packages required for file previews
  apt:
    pkg:
      - libcdio-utils
      - p7zip-full
      - unrar
      - odt2txt
      - catdoc
      - docx2txt
      - ffmpegthumbnailer
      - libimage-exiftool-perl
      - xdotool
      - highlight
      - atool
      - bat
      - mediainfo
      - lynx

# TODO: ueberzug not maintained, find alternative
# - name: Install ueberzug (pip)
#   pip:
#     name:
#       - ueberzug
