---
# TODO: install kubectl, yq

- import_tasks: ./packages.yml
- import_tasks: ./spotify.yml
- import_tasks: ./lazygit.yml
- import_tasks: ./gradle.yml
- import_tasks: ./anki.yml
- import_tasks: ./spring.yml
- import_tasks: ./ytdlp.yml
- import_tasks: ./jetbrains.yml
- import_tasks: ./tt.yml
- import_tasks: ./lf.yml
- import_tasks: ./chrome.yml
- import_tasks: ./syncthing.yml
- import_tasks: ./firefox.yml
# - import_tasks: ./transmission.yml

