---
- name: Install a bunch of software from apt (this might take a while)
  apt:
    pkg:
      - age
      - autorandr
      - cmatrix
      - curl
      - dunst
      - expect
      - flameshot
      - fuse
      - fzf
      - gimp
      - gir1.2-nm-1.0
      - htop
      - jq
      - libfuse2
      - lxrandr
      - mdp
      - moreutils
      - mpv
      - ncal
      - neofetch
      - net-tools
      - network-manager-gnome
      - openjdk-11-jdk
      - openjdk-17-jdk
      - openvpn-systemd-resolved
      - parallel
      - psmisc # killall
      - pulsemixer
      - python3-pip
      - ranger
      - redshift
      - software-properties-common
      - sxiv
      - thunar
      - tmux
      - tree
      - virt-manager
      - virtualenv
      - vlc
      - xclip
      - zathura

- name: Make sure java 11 is still default
  shell:
    cmd: update-java-alternatives -s java-1.11.0-openjdk-amd64
  changed_when: false
