---
- name: Install a bunch of software from apt (this might take a while)
  apt:
    pkg: 
      - software-properties-common
      - curl
      - lxrandr
      - autorandr
      - net-tools
      - jq
      - neofetch
      - fzf
      - xclip
      - mdp
      - htop
      - ranger
      - tmux
      - expect
      - cmatrix
      - tree
      - pulsemixer
      - gimp
      - net-tools
      - ncal
      - fuse
      - libfuse2
      - mpv
      - vlc
      - redshift
      - zathura
      - thunar
      - dunst
      - flameshot

