---
- name: Install a bunch of software
  apt:
    pkg: 
      - curl
      - lxrandr
      - xvkbd
      - xbindkeys
      - unclutter
      - net-tools
      - jq
      - neofetch
      - fzf
      - xclip
      - mdp
      - htop
      - ranger
      - tmux
      - expect
      - cmatrix
      - tree
      - pulsemixer
      - software-properties-common
      - gimp
      - net-tools
      - ncal
      - fuse
      - libfuse2
