---
- name: Install sops
  include_tasks: util/download_file.yml
  vars:
    dl_url: https://github.com/getsops/sops/releases/download/v3.8.1/sops-v3.8.1.linux.amd64
    dl_filename: sops
    dl_dest_dir: "{{ dotfiles_data_dir }}/sops"
    dl_link_file_path: "{{ dl_dest_dir }}/sops"
    dl_link_file_dest: /usr/local/bin/sops

