---
- name: Install syncthing
  become: true
  apt:
    name: syncthing
    state: present

# syncthing.service user-level systemd enable is in xinitrc

- name: Delete the default Sync dir
  file:
    state: absent
    path: "/home/{{ username }}/Sync"

# this needs some manual setup...
