---
- name: Install syncthing
  apt:
    name: syncthing
    state: present

# syncthing.service user-level systemd enable is in xinitrc

- name: Create syncthing folder
  file:
    state: directory
    path: /st
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Delete the default Sync dir
  file:
    state: absent
    path: "/home/{{ username }}/Sync"

# this needs some manual setup...
