---
- name: Ensure transmission is installed
  become: true
  apt:
    pkg:
      - transmission
      - transmission-daemon

- name: Make transmission directory
  become: true
  file:
    path: /log/transmission
    state: directory
    mode: 0777
    group: root
    owner: root

- name: remove transmission daemon authentication
  become: true
  lineinfile:
    path: /etc/transmission-daemon/settings.json
    regexp: ' *"rpc-authentication-required":'
    line: "    \"rpc-authentication-required\": false,"
  register: transmission_auth

- name: change transmission download dir
  become: true
  lineinfile:
    path: /etc/transmission-daemon/settings.json
    regexp: ' *"download-dir":'
    line: "    \"download-dir\": \"/log/transmission\","
  register: transmission_dir

- name: reload transmission daemon
  become: true
  command: /etc/init.d/transmission-daemon reload
  when: transmission_auth.changed or transmission_dir.changed
