---
# ╔═════════════════════════════════╗
# ║ Intended to run on Ubuntu 22.04 ║
# ╚═════════════════════════════════╝
- name: "Configure my pc (root)"
  become: true
  become_method: sudo
  hosts: localhost
  connection: local

  vars_files:
    - ./vars/main.yml
    # - ./config_personal/vars/main.yml

  pre_tasks:
    - name: Ensure /usr/local/bin exists
      file:
        dest: /usr/local/bin
        state: directory
        mode: 0755

  tasks:
    - import_role:
        name: system
      tags: [init, system]
    - import_role:
        name: fonts
      tags: [init, fonts]
    # - import_role:
    #     name: geerlingguy.nodejs
    #   tags: [init, software]
    #   vars:
    #     nodejs_version: "18.x"
    #     nodejs_install_npm_user: "{{ username }}"
    - import_role:
        name: nvim
      tags: [init, nvim]
    - import_role:
        name: dotfiles
      tags: [init, dotfiles]
    - import_role:
        name: desktop
      tags: [init, desktop]
    - import_role:
        name: geerlingguy.docker
      when: not vm
      tags: [software]
      vars:
        docker_daemon_options:
          bip: "172.20.0.1/24"
          default-address-pools:
            - base: 172.20.0.0/16
              size: 24
    - import_role:
        name: software
      tags: [software]
    # - import_role:
    #     name: virt
    #   tags: [virt]
