---
# ╔═════════════════════════════════╗
# ║ Intended to run on Ubuntu 22.04 ║
# ╚═════════════════════════════════╝
- name: "Configure my pc (user)"
  hosts: localhost
  connection: local

  vars_files:
    - ./vars/main.yml
    - ./config_personal/vars.yml

  tasks:
    - import_role:
        name: repos
      tags:
        - repos
