---
# https://github.com/openzfs/zfs/issues/9461#issuecomment-699889066
- name: /etc/fstab
  become: true
  ansible.builtin.copy:
    dest: /etc/fstab
    content: |
      {{ dotfiles_root_zfs_dataset }} / zfs defaults,noatime 0 0

- name: /etc/sanoid/sanoid.conf
  become: true
  ansible.builtin.copy:
    dest: /etc/sanoid/sanoid.conf
    content: |
      [{{ dotfiles_root_zfs_dataset }}]
          use_template = root

      [template_root]
          frequently = 3
          hourly = 3
          daily = 4
          monthly = 1
          yearly = 0
          autosnap = yes
          autoprune = yes

- name: /etc/profile.d/global_env.sh
  become: true
  ansible.builtin.copy:
    dest: /etc/profile.d/global_env.sh
    content: |
      #!/bin/sh

      export PATH=$PATH:~/.local/bin:~/.bin
      export BROWSER=google-chrome
      export EDITOR=nvim
      export VISUAL=nvim
      export CONFDIR=/data

- name: /etc/netplan/netcfg.yaml
  become: true
  ansible.builtin.copy:
    dest: /etc/netplan/netcfg.yaml
    content: |
      network:
        ethernets:
          all:
            match:
              name: e*
            dhcp4: true
