---
- name: "Create {{ dotfiles_data_dir }}/fonts"
  become: true
  file:
    path: "/{{ dotfiles_data_dir }}/fonts"
    state: directory
    mode: 0755
    group: root
    owner: root

- name: Download UbuntuMono nerdfont from github
  include_tasks: util/download_file.yml
  vars:
    dl_url: "https://github.com/ryanoasis/nerd-fonts/releases/latest/download/UbuntuMono.zip"
    dl_filename: "UbuntuMono.zip"
    dl_unarchive: yes
    dl_unarchive_dir: "{{ dotfiles_data_dir }}/fonts/UbuntuMono"

- name: Copy UbuntuMono font to /usr/share/fonts
  become: true
  synchronize:
    src: "/{{ dotfiles_data_dir }}/fonts/UbuntuMono"
    dest: /usr/share/fonts/
  register: font_copy

- name: Update font cache
  become: true
  when: font_copy.changed
  command: fc-cache -f
  changed_when: false

