---
# src: https://www.maximilian-schillinger.de/articles/st-libxft-bgra-patch.html
# TODO: untested (gitlab.freedesktop.com is down)

- name: "Create {{ confdir }}/libs"
  file:
    path: "{{ confdir }}/libs"
    state: directory
    mode: 0755
    group: root
    owner: root

- name: "Clone libxft repo"
  git:
    repo: https://gitlab.freedesktop.org/xorg/lib/libxft
    dest: "{{ confdir }}/libs/libxft"
    version: master
    depth: 1
    update: no
  register: libxft_clone

- name: "fetch"
  when: libxft_clone.changed
  command: git fetch https://gitlab.freedesktop.org/mawww/libxft.git bgra-glyphs
  changed_when: false
  args:
    chdir: "{{ confdir }}/libs/libxft"

- name: "checkout"
  when: libxft_clone.changed
  command: "sh -c \"git checkout mawww/libxft-bgra-glyphs || git checkout -b mawww/libxft-bgra-glyphs FETCH_HEAD\""
  changed_when: false
  args:
    chdir: "{{ confdir }}/libs/libxft"

- name: "Install required packages to build libxft-bgra"
  when: libxft_clone.changed
  apt:
    pkg:
      - build-essential
      - libtool
      - pkg-config
      - libxrender-dev
      - libfreetype6-dev
      - libfontconfig1-dev
      - xutils-dev

- name: "build libxft-bgra"
  when: libxft_clone.changed
  command: "sh autogen.sh --sysconfdir=/etc --prefix=/usr --mandir=/usr/share/man"
  changed_when: false
  args:
    chdir: "{{ confdir }}/libs/libxft"

- name: "build libxft-bgra"
  when: libxft_clone.changed
  command: "make"
  changed_when: false
  args:
    chdir: "{{ confdir }}/libs/libxft"
