---
- name: "Create {{ confdir }}"
  file:
    path: "{{ confdir }}"
    state: directory
    mode: 0755
    group: root
    owner: root

- name: "Clone luastatus repo"
  git:
    repo: https://github.com/shdown/luastatus
    dest: "{{ confdir }}/luastatus"
    version: master
    depth: 1
    update: yes
  register: clone_luastatus

- name: build luastatus
  when: clone_luastatus.changed
  command: "cmake ."
  args:
    chdir: "{{ confdir }}/luastatus"
  changed_when: false

- name: build luastatus
  when: clone_luastatus.changed
  command: "make"
  args:
    chdir: "{{ confdir }}/luastatus"
  changed_when: false

- name: build luastatus
  when: clone_luastatus.changed
  command: "make install"
  args:
    chdir: "{{ confdir }}/luastatus"
  changed_when: false
