---
- name: "Create {{ confdir }}"
  become: true
  file:
    path: "{{ confdir }}"
    state: directory
    mode: 0755
    group: root
    owner: root

- import_tasks: ./apt.yml
- import_tasks: ./fonts.yml
- import_tasks: ./zfs.yml

- import_tasks: ./nvim.yml
- import_tasks: ./dotfiles.yml

- import_tasks: ./de/dwm.yml
- import_tasks: ./de/st.yml
- import_tasks: ./de/dmenu.yml
- import_tasks: ./de/luastatus.yml
- import_tasks: ./de/slock.yml

- import_tasks: ./security.yml
- import_tasks: ./etc.yml
- import_tasks: ./cleanup.yml

