---
- name: install picom
  apt:
    name: 
      - picom
    state: present

- import_tasks: ./libxft_bgra.yml # needs to be done first
- import_tasks: ./dwm.yml
- import_tasks: ./st.yml
- import_tasks: ./dmenu.yml
- import_tasks: ./luastatus.yml
- import_tasks: ./slock.yml

