---
- name: Install neovim related packages
  become: true
  apt:
    name:
      - lua5.1
      - luarocks
      - python-is-python3
      - ripgrep
      - fzf
      - shellcheck
      - shfmt
      - python3-pynvim
      - fd-find
    state: present

- name: Download, unarchive and link nvim
  include_tasks: util/download_file.yml
  vars:
    dl_url: "https://github.com/neovim/neovim/releases/latest/download/nvim.appimage"
    dl_filename: "nvim.appimage"
    dl_dest_dir: "{{ confdir }}/nvim-releases"

- name: Install neovim
  become: true
  copy:
    src: "{{ confdir }}/nvim-releases/nvim.appimage"
    dest: "/usr/local/bin/nvim"
    owner: root
    group: root
    mode: '0755'
  register: nvim_install

- name: remove .config/nvim
  become: true
  when: nvim_install.changed
  file:
    dest: "/home/{{ username }}/.config/nvim"
    state: absent

- name: Git clone astronvim
  when: nvim_install.changed
  become: true
  become_user: "{{ username }}"
  ansible.builtin.git:
    repo: https://github.com/AstroNvim/AstroNvim
    dest: "/home/{{ username }}/.config/nvim"
    update: no
