---
# Do this before software role so that startx doesn't crash
- name: Install some desktop-specific packages (.xinitrc requirements, suckless build requirements)
  apt:
    pkg:
      - autorandr
      - build-essential
      - cmake
      - feh
      - libasound2-dev
      - libfontconfig1-dev
      - libfreetype6-dev
      - libharfbuzz-dev
      - liblua5.1-0-dev
      - libnl-3-dev
      - libnl-genl-3-dev
      - libpam0g-dev
      - libtool
      - libudev-dev
      - libx11-dev
      - libx11-xcb-dev
      - libxcb-ewmh-dev
      - libxcb-icccm4-dev
      - libxcb-res0-dev
      - libxcb-xrm-dev
      - libxft-dev
      - libxinerama-dev
      - libxrandr-dev
      - libxrender-dev
      - libyajl-dev
      - lua5.1
      - picom
      - pkg-config
      - python3-docutils
      - sxhkd
      - unclutter
      - xbindkeys
      - xcape
      - xcb
      - xdotool
      - xutils-dev
      - xvkbd

- name: Remove autorandr service
  file:
    dest: /lib/systemd/system/autorandr.service
    state: absent
  register: autorandr_service

- name: Reload system-daemon
  when: autorandr_service.changed
  shell: systemctl daemon-reload
