---
# Do this before software role so that startx doesn't crash
- name: Install some desktop-specific packages (everything in .xinitrc)
  apt:
    pkg:
      - xvkbd
      - xbindkeys
      - sxhkd
      - feh
      - xcape
      - unclutter

- name: Install picom (if not vm)
  when: not vm
  apt:
    pkg:
      - picom

- name: Remove autorandr service
  file:
    dest: /lib/systemd/system/autorandr.service
    state: absent
  register: autorandr_service

- name: Reload system-daemon
  when: autorandr_service.changed
  shell: systemctl daemon-reload
