---
- name: Install some desktop-specific packages (everything in .xinitrc)
  apt:
    pkg:
      - xvkbd
      - xbindkeys
      - sxhkd
      - feh
      - xcape
      - autorandr
      - picom
      - unclutter

- name: Remove autorandr service
  file:
    dest: /lib/systemd/system/autorandr.service
    state: absent
  register: autorandr_service

- name: Reload system-daemon
  when: autorandr_service.changed
  shell: systemctl daemon-reload
