---
- name: Remove autorandr service
  become: true
  file:
    dest: /lib/systemd/system/autorandr.service
    state: absent
  register: autorandr_service

- name: Reload system-daemon
  become: true
  when: autorandr_service.changed
  shell: systemctl daemon-reload

- name: Clean up some default directories
  become: true
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "/home/{{ username }}/Desktop"
    - "/home/{{ username }}/Music"
    - "/home/{{ username }}/Public"
    - "/home/{{ username }}/Templates"
    - "/home/{{ username }}/.profile"
