---
- name: Remove gnome, ubuntu desktop DE
  become: true
  apt:
    pkg: 
      - gedit-common
      - gir1.2-gdm-1.0 
      - gir1.2-gnomebluetooth-1.0
      - gir1.2-gnomedesktop-3.0
      - gir1.2-goa-1.0 
      - gnome-*
      - language-pack-gnome-*
      - language-pack-gnome-en-base
      - language-pack-gnome-ru 
      - language-selector-gnome
      - libgail18
      - libgnome-autoar-0-0
      - libgnome-bluetooth13 
      - libgnome-desktop-3-19
      - libgnome-games-support-1-3
      - libgnome-games-support-common 
      - libgnomekbd8
      - libgnomekbd-common
      - libgnome-menu-3-0
      - libgnome-todo
      - libgoa-1.0-0b 
      - libgoa-1.0-common
      - libpam-gnome-keyring
      - nautilus-extension-gnome-terminal
      - pinentry-gnome3
      - yaru-theme-gnome-shell
    state: absent
    purge: true
    autoremove: true
  when: remove_gnome

- name: Install xorg
  apt:
    name: xorg
    state: present

- name: Remove gdm3 (comes with xorg)
  apt:
    name: gdm3
    state: absent
  when: remove_gnome
