---
- name: Update grub to boot to text terminal login, disable recovery
  lineinfile:
    dest: /etc/default/grub
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
    mode: 0644
  with_items:
    - regexp: "^GRUB_CMDLINE_LINUX_DEFAULT"
      line: 'GRUB_CMDLINE_LINUX_DEFAULT=""'
    - regexp: "^GRUB_TERMINAL"
      line: 'GRUB_TERMINAL=console'
    - regexp: "^GRUB_DISABLE_RECOVERY"
      line: 'GRUB_DISABLE_RECOVERY="true"'
  register: modify_grub

- name: update grub
  command: update-grub
  become: true
  when: modify_grub.changed
