---
# TODO: this is slow and crashes on first run
# - name: apt update, upgrade
#   become: true
#   apt:
#     upgrade: yes
#     update_cache: yes
#     cache_valid_time: 86400 #One day

- name: "Create {{ confdir }}"
  file:
    path: "{{ confdir }}"
    state: directory
    mode: 0755
    group: root
    owner: root

- name: copy over global_env.sh
  copy:
    src: files/global_env.sh
    dest: /etc/profile.d/global_env.sh
    owner: root
    group: root
    mode: 0664

- import_tasks: ./packages.yml
- import_tasks: ./zfs.yml
  when: not vm
- import_tasks: ./grub.yml
- import_tasks: ./gnome_cleanup.yml
- import_tasks: ./nosnap.yml
- import_tasks: ./yubikey.yml

- name: "disable any action on close lid"
  lineinfile:
    path: "/etc/systemd/logind.conf"
    regexp: "^HandleLidSwitch.*"
    line: "HandleLidSwitch=ignore"
