---
- name: Download, unarchive and link nvim
  include_tasks: util/download_file.yml
  vars:
    dl_url: "https://github.com/neovim/neovim/releases/latest/download/nvim.appimage"
    dl_filename: "nvim.appimage"
    dl_dest_dir: "{{ dotfiles_data_dir }}/nvim-releases"

- name: Install neovim
  become: true
  copy:
    src: "{{ dotfiles_data_dir }}/nvim-releases/nvim.appimage"
    dest: "/usr/local/bin/nvim"
    owner: root
    group: root
    mode: "0755"
