---
- name: Install some system packages (needed for ansible file handlers)
  apt:
    name: 
      - software-properties-common
      - curl
      - unzip
      - rsync
      - dbus
      - bluez
      - bluez-alsa-utils
      - pulseaudio-module-bluetooth
      - dnsutils
    state: present
