---
- name: Add yubico repository
  ansible.builtin.apt_repository:
    repo: ppa:yubico/stable
    state: present

- name: Install some system packages (needed for ansible file handlers)
  apt:
    state: present
    name: 
      - bluez
      - bluez-alsa-utils
      - curl
      - dbus
      - dnsutils
      - gnupg
      - pcscd
      - pinentry-qt
      - pulseaudio-module-bluetooth
      - rsync
      - sanoid
      - scdaemon
      - software-properties-common
      - unzip
      - yubikey-manager
