---
- name: Ensure firewall is enabled
  become: true
  community.general.ufw:
    state: enabled
    default: deny

- name: Check ufw rules
  become: true
  command: "ufw status numbered | wc -l"
  register: ufw_status
  changed_when: false

- name: Reset firewall rules (remove any user alterations)
  become: true
  community.general.ufw:
    state: reset
  when: ufw_status.stdout_lines | length > 1

- name: Ensure firewall is enabled
  become: true
  community.general.ufw:
    state: enabled
    default: deny
  when: ufw_status.stdout_lines | length > 1

- name: Disallow SSH password authentication
  become: true
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PasswordAuthentication"
    line: "PasswordAuthentication no"
    state: present
  register: sshd_config

- name: Restart SSHD if configuration changed
  become: true
  service:
    name: ssh
    state: restarted
  when: sshd_config.changed
