---
- name: Install sanoid (automatic zfs snapshots)
  apt:
    name: sanoid
    state: present

- name: Ensure /etc/sanoid/ exists
  file:
    path: /etc/sanoid
    state: directory
    mode: 0755
    owner: root

- name: Copy over sanoid.conf 
  synchronize:
    src: files/sanoid.conf
    dest: /etc/sanoid/sanoid.conf

- name: Disable default sanoid timer (systemd)
  systemd:
    name: sanoid.timer
    enabled: no
    state: stopped

- name: Disable default sanoid-prune service (systemd)
  systemd:
    name: sanoid-prune.service
    enabled: no
    state: stopped

- name: Add cron entry for sanoid
  cron:
    name: "sanoid"
    job: "sanoid --cron"
    user: root

- name: Create docker dataset
  shell: "zfs create -o mountpoint=/docker zroot/docker"
  failed_when: false
  changed_when: false

- name: Make zfs snapshots visible under /.zfs/snapshot/
  shell: "zfs set snapdir=visible zroot/ROOT/ubuntu"
  changed_when: false

# https://github.com/openzfs/zfs/issues/9461#issuecomment-699889066
- name: zfs snapdir issue workaround
  lineinfile: 
    path: /etc/fstab
    regexp: '^zroot'
    line: zroot/ROOT/ubuntu / zfs defaults,noatime 0 0

