---
- name: Ensure /etc/sanoid/ exists
  file:
    path: /etc/sanoid
    state: directory
    mode: 0755
    owner: root

- name: Copy over sanoid.conf 
  synchronize:
    src: files/sanoid.conf
    dest: /etc/sanoid/sanoid.conf

- name: Create docker dataset
  community.general.zfs:
    name: zroot/docker
    state: present
    extra_zfs_properties:
      mountpoint: /docker

- name: Make zfs snapshots visible under /.zfs/snapshot/
  shell: "zfs set snapdir=visible zroot/ROOT/ubuntu"
  changed_when: false

# https://github.com/openzfs/zfs/issues/9461#issuecomment-699889066
- name: zfs snapdir issue workaround
  lineinfile: 
    path: /etc/fstab
    regexp: '^zroot'
    line: zroot/ROOT/ubuntu / zfs defaults,noatime 0 0

