---
- name: Create docker dataset
  become: true
  community.general.zfs:
    name: zroot/docker
    state: present
    extra_zfs_properties:
      mountpoint: /docker

- name: Make zfs snapshots visible under /.zfs/snapshot/
  become: true
  shell: "zfs set snapdir=visible {{ dotfiles_root_zfs_dataset }}"
  changed_when: false
