---
- name: Clone vscode-gradle
  become: yes
  become_user: "{{ username }}"
  git:
    depth: 1
    repo: https://github.com/microsoft/vscode-gradle
    dest: "/home/{{ username }}/.local/ls/gradle"
  register: clone_gradle

- name: Build vscode-gradle
  when: clone_gradle.changed
  become: yes
  become_user: "{{ username }}"
  command: ./gradlew installDist
  environment:
    JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64
  args:
    chdir: "/home/{{ username }}/.local/ls/gradle"

