---
- name: Download eclipse jdtls
  become: yes
  become_user: "{{ username }}"
  get_url:
    url: "{{ nvim_jdtls_server }}"
    dest: "/home/{{ username }}/.local/ls/java/jdtls.tar.gz"
  register: jdtls

- name: Create ~/.local/ls/java/jdtls
  file:
    state: directory
    recurse: yes
    path: "/home/{{ username }}/.local/ls/java/jdtls"
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Clean up existing jdtls directory
  when: jdtls.changed
  file:
    state: absent
    path: "/home/{{ username }}/.local/ls/java/jdtls/*"

- name: unpack jdtls
  when: jdtls.changed
  unarchive:
    src: "/home/{{ username }}/.local/ls/java/jdtls.tar.gz"
    dest: "/home/{{ username }}/.local/ls/java/jdtls"
