---
- name: Create ~/.local/ls/java
  file:
    state: directory
    recurse: yes
    path: "/home/{{ username }}/.local/ls/java"
    owner: "{{ username }}"
    group: "{{ username }}"

- import_tasks: ./jdtls.yml
- import_tasks: ./microsoft-java-debug.yml
- import_tasks: ./vscode-java-test.yml

- name: Set ~/.local/ls permissions
  file:
    state: directory
    recurse: yes
    dest: "/home/{{ username }}/.local/ls/java"
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Make sure java 11 is still default
  shell:
    cmd: update-java-alternatives -s java-1.11.0-openjdk-amd64
  changed_when: false

# - name: Create apps folder
#   file:
#     path: ~/apps/
#     state: directory
#     mode: 0700
# - name: Create async-profiler folder
#   file:
#     path: ~/apps/async-profiler/
#     state: directory
#     mode: 0700
#
#
# - name: Fetch sjk.jar
#   get_url:
#     url: https://repository.sonatype.org/service/local/artifact/maven/redirect?r=central-proxy&g=org.gridkit.jvmtool&a=sjk&v=LATEST
#     dest: ~/apps/sjk.jar
#
# - name: Get and unpack async-profiler
#   unarchive:
#     src: https://github.com/jvm-profiling-tools/async-profiler/releases/download/v2.7/async-profiler-2.7-linux-x64.tar.gz
#     dest: ~/apps/async-profiler/
#     remote_src: true
#     creates: ~/apps/async-profiler/profiler.sh
#     extra_opts:
#       - --strip-components=1
#
# - name: Get jfr converter
#   get_url:
#     url: https://github.com/jvm-profiling-tools/async-profiler/releases/download/v2.7/converter.jar
#     dest: ~/apps/converter.jar
#
#
# - name: Create jmc folder
#   file:
#     path: ~/apps/jmc/
#     state: directory
#     mode: 0700
# - name: Get and unpack jmc
#   unarchive:
#     src: https://github.com/adoptium/jmc-build/releases/download/8.3.0-SNAPSHOT/org.openjdk.jmc-8.3.0-SNAPSHOT-linux.gtk.x86_64.tar.gz
#     dest: ~/apps/jmc/
#     remote_src: true
#     creates: ~/apps/jmc/bin/jmc
#     extra_opts:
#       - --strip-components=1
# - name: Create symlink for jmc
#   file:
#     src: ~/apps/jmc/jmc
#     dest: ~/bin/jmc
#     state: link
#
# - name: Clone vscode-java-decompiler
#   git:
#     repo: https://github.com/dgileadi/vscode-java-decompiler
#     dest: ~/dev/dgileadi/vscode-java-decompiler
#
# - name: Clone vscode-pde
#   git:
#     repo: https://github.com/testforstephen/vscode-pde
#     dest: ~/dev/testforstephen/vscode-pde
#     force: true  # npm commands below modify the package.json
#
# - name: Build vscode-pde
#   command: npm install
#   environment:
#     JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64
#   args:
#     chdir: ~/dev/testforstephen/vscode-pde/
