---
- name: Install virtualization packages
  apt:
    pkg:
      - qemu-kvm
      - libvirt-clients
      - libvirt-daemon-system
      - bridge-utils
      - virtinst
      - libvirt-daemon
      - virt-manager
      - guestfs-tools

