---
- name: build st
  become: true
  shell: FLEXIPATCH=st ./run.sh
  args:
    chdir: home/.config/st
  register: st
  changed_when: "'TASK_CHANGED' in st.stdout"

- name: Ensure /usr/share/applications exists
  become: true
  when: st.changed
  file:
    path: /usr/share/applications
    state: directory

- name: add st.desktop xsession entry
  become: true
  when: st.changed
  copy:
    src: ../files/st.desktop
    dest: /usr/share/applications/st.desktop
