---
# - name: Add neovim nightly ppa
#   ansible.builtin.apt_repository:
#     repo: ppa:neovim-ppa/unstable
#     state: present

# TODO: download nvim.appimage to /usr/local/bin/nvim
- name: Download, unarchive and link ytdlp
  include_tasks: util/download_file.yml
  vars:
    dl_url: "https://github.com/neovim/neovim/releases/latest/download/nvim.appimage"
    dl_filename: "nvim.appimage"
    dl_dest_dir: "{{ confdir }}/nvim-releases"

- name: Install neovim
  copy:
    src: "{{ confdir }}/nvim-releases/nvim.appimage"
    dest: "/usr/local/bin/nvim"
    owner: root
    group: root
    mode: '0755'
  register: nvim_install

- name: remove .config/nvim
  when: nvim_install.changed
  file:
    dest: "/home/{{ username }}/.config/nvim"
    state: absent

- name: Git clone astronvim
  when: nvim_install.changed
  become: true
  become_user: "{{ username }}"
  ansible.builtin.git:
    repo: https://github.com/AstroNvim/AstroNvim
    dest: "/home/{{ username }}/.config/nvim"
    update: no

- name: Install neovim and related packages
  apt:
    name:
      - lua5.1
      - luarocks
      - python-is-python3
      - ripgrep
      - fzf
      - shellcheck
      - shfmt
      - python3-pynvim
      - npm
      - fd-find
    state: present

# - import_tasks: ./formatters.yml
- import_tasks: ./java/main.yml

