---
- name: Add neovim nightly ppa
  ansible.builtin.apt_repository:
    repo: ppa:neovim-ppa/unstable
    state: present

- name: Install neovim and related packages
  apt:
    name:
      - neovim
      - lua5.1
      - luarocks
      - python-is-python3
      - ripgrep
      - fzf
      - shellcheck
      - python3-pynvim
    state: present

- name: Upgrade npm to latest version
  npm:
    name: npm
    global: true
    state: latest

- import_tasks: ./packer.yml
- import_tasks: ./java/main.yml

