---
# - name: Add neovim nightly ppa
#   ansible.builtin.apt_repository:
#     repo: ppa:neovim-ppa/unstable
#     state: present
- name: Download, unarchive and link ytdlp
  include_tasks: util/download_file.yml
  vars:
    dl_url: "{{ nvim_deb }}"
    dl_filename: "nvim-linux64.deb"
    dl_dest_dir: "{{ confdir }}/nvim-releases"

- name: Install neovim deb package
  when: download_file_changed
  apt:
    deb: "{{ confdir }}/nvim-releases/nvim-linux64.deb"

- name: Git clone astronvim
  become: yes
  become_user: "{{ username }}"
  ansible.builtin.git:
    repo: https://github.com/AstroNvim/AstroNvim
    dest: "/home/{{ username }}/.config/nvim"
    update: no

- name: Install neovim and related packages
  apt:
    name:
      - neovim
      - lua5.1
      - luarocks
      - python-is-python3
      - ripgrep
      - fzf
      - shellcheck
      - shfmt
      - python3-pynvim
    state: present

- name: Upgrade npm to latest version
  npm:
    name: npm
    global: true
    version: 8.1
    state: present

- import_tasks: ./formatters.yml
- import_tasks: ./packer.yml
- import_tasks: ./java/main.yml

