---
- name: Add neovim nightly ppa
  ansible.builtin.apt_repository:
    repo: ppa:neovim-ppa/unstable
    state: present

- file:

- name: Install neovim
  apt:
    name: neovim
    state: present

- name: Install some neovim plugin dependencies
  apt:
    pkg: 
    - ripgrep
    - fzf
    state: present

- name: Install some packages needed for linting
  apt:
    pkg: 
    - shellcheck
    state: present

- name: Install pynvim
  apt:
    pkg: python3-pynvim
    state: present

- name: Upgrade npm to latest version
  npm:
    name: npm
    global: true
    state: latest

- import_tasks: ./packer.yml
- import_tasks: ./java/main.yml

