---
- name: make ~/.local/share/nvim/site/pack/packer directory
  file:
    state: directory
    dest: "/home/{{ username }}/.local/share/nvim/site/pack/packer"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0754

- name: Clone packer.nvim to ~/.local/share/nvim/site/pack/packer/start/packer.nvim
  become: true
  become_user: "{{ username }}"
  git:
    repo: https://github.com/wbthomason/packer.nvim
    dest: "/home/{{ username}}/.local/share/nvim/site/pack/packer/start/packer.nvim"
    update: no

- name: Set correct permissions for packer directory
  file:
    state: directory
    recurse: yes
    dest: "/home/{{ username }}/.local/share/nvim/site/pack/packer"
    owner: "{{ username }}"
    group: "{{ username }}"
