---
- name: "Create /{{ confdir }}/fonts"
  file:
    path: "/{{ confdir }}/fonts"
    state: directory
    mode: 0755
    group: root
    owner: root

- name: Download and install lf
  include_tasks: util/download_file.yml
  vars:
    dl_url: "{{ fonts_ubuntu_mono }}"
    dl_filename: "UbuntuMono.zip"
    dl_unarchive: yes
    dl_unarchive_dir: "{{ confdir }}/fonts/UbuntuMono"

- name: "Copy UbuntuMono font to /usr/share/fonts"
  synchronize:
    src: "/{{ confdir }}/fonts/UbuntuMono"
    dest: /usr/share/fonts/
  register: copy

- debug:
    var: copy

- name: " Update font cache"
  command: fc-cache -f
  changed_when: false
